### ISSUE TITLE
Any chance of upgrading to ebean 7.18.1?

### ISSUE THREAD

**Issue by jfendler** [ninjaframework/ninja-ebean#7]
The ebean dependency is quite a bit outdated by now. What are the chances of an upgrade some time soon?

**Comment by raphaelbauer** [comment]
PRs are welcome :) @jjlauer is the best person to talk to...

**Comment by jfendler** [comment]
That's what I thought... ;-) My backlog just doesn't get any shorter...

I'll see what I can do.

**Comment by jjlauer** [comment]
The current module's ebean dependency is more of the minimum compat version
than the recommended one.  We use v7.2.3 in our projects.

We can't go any higher than that w/o changing the ninja module due to the
ebean orm finally breaking backwards compat on version > 7.2.3.  If we find
a reason/feature, we'll submit a PR, but for now v7.2.3 works well for us.

-Joe

**Comment by jfendler** [comment]
@jjlauer, thanks for the pointer to the last working version. That's what I use in my existing projects as well.

However, to keep up with EBean's development, I have taken the liberty to blatantly copy and paste the module, and to provide a "ninja-ebean-ng-module" for the latest versions of EBean.

So, @raphaelbauer, instead of a PR, we now have two separate EBean modules, which are using the (99%) exact same code, but have different maven dependencies: [ninja-ebean-ng](https://github.com/jfendler/ninja-ebean-ng)

This way people who want to use the old EBean API can still use the original module, while people starting with new projects, or wanting to use the EBean Query API can use the "ng" module with post-7.2.3 support.

Thanks a lot to both of you for doing the harder work of bringing up this module in the first place.

**Comment by raphaelbauer** [comment]
Sounds legit... :)
